name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      build_context:
        description: 'Path to the build context'
        required: true
        type: string
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
      image_version:
        description: 'Version/tag for the Docker image'
        required: true
        type: string
      runs_on:
        description: 'The type of runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up GitHub Actions environment
        run: echo "GITHUB_ACTOR_LOWER=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.build_context }}
          push: true
          tags: ghcr.io/${{ env.GITHUB_ACTOR_LOWER }}/${{ inputs.image_name }}:${{ inputs.image_version }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}