name: Build ROS Containers

on:
  push:
    # branches: [ main, master ]
    tags:
      - 'dev*'  # This will trigger on any tag starting with 'dev', like dev1.0.0
      - 'v*'  # This will trigger on any tag starting with 'v', like v1.0.0
  # pull_request:
  #   branches: [ main, master ]

jobs:
  get_tags:
    name: ROS2 Humble Base Images (AMD64)
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.image_name.outputs.image_version }}
    permissions:
      packages: write
      contents: read
      pull-requests: write
    steps:
      - name: Set up GitHub Actions environment
        id: image_name
        run: |
          echo "image_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
  main_build:
    needs: get_tags
    name: Build and push Docker image  
    uses: ./.github/workflows/build-workflow.yaml
    permissions:
      packages: write
      contents: read
      pull-requests: write
    with:
      build_context: .devcontainer
      image_name: koide3_calibration
      image_version: ${{ needs.get_tags.outputs.image_version }}
      runs_on: ubuntu-latest